### Send POST request with json body
POST http://pro.loc:86/api/books
Content-Type: application/json
Accept: application/json

{
    "name": "NewBookCat12345678970",
    "year": "2023",
    "lang": "ua",
    "pages": "123",
    "categoryId": "2"
}
