<?php

namespace Numbers;

use App\Services\Numbers\LessNumberService;
use PHPUnit\Framework\TestCase;

class LessNumberTest extends TestCase
{
    protected LessNumberService $lessNumberService;
    protected array $numbers;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->numbers = [
            '1',
            '2',
            '26'
        ];

        $this->lessNumberService = new LessNumberService($this->numbers);
    }

    public function testLess()
    {
        $less = $this->lessNumberService->getLess();
        $this->assertSame(2, $less);
    }

}
