<?php

namespace Numbers;

use App\Services\Numbers\EvenNumberService;
use App\Services\Numbers\LessNumberService;
use App\Services\Numbers\OddNumberService;
use App\Services\Numbers\OverEvenNumberService;
use PHPUnit\Framework\TestCase;

class NumberTest extends TestCase
{
    protected EvenNumberService $evenNumberService;
    protected OddNumberService $oddNumberService;
    protected LessNumberService $lessNumberService;
    protected OverEvenNumberService $overEvenNumberService;

    protected array $numbers;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->numbers = [
            '1',
            '2',
            '26'
        ];
        $this->evenNumberService = new EvenNumberService($this->numbers);
        $this->oddNumberService = new OddNumberService($this->numbers);
        $this->lessNumberService = new LessNumberService($this->numbers);
        $this->overEvenNumberService = new OverEvenNumberService($this->numbers);
    }

    public function testEven()
    {
        $even = $this->evenNumberService->getEven();
        $this->assertSame(2, $even);
    }

    public function testOdd()
    {
        $odd = $this->oddNumberService->getOdd();
        $this->assertSame(1, $odd);
    }

    public function testLess()
    {
        $less = $this->lessNumberService->getLess();
        $this->assertSame(2, $less);
    }

    public function testOverEven()
    {
        $overEven = $this->overEvenNumberService->getOverEven();
        $this->assertSame(1, $overEven);
    }

}
