<?php

namespace Numbers;

use App\Services\Numbers\OddNumberService;
use PHPUnit\Framework\TestCase;

class OddNumberTest extends TestCase
{
    protected OddNumberService $oddNumberService;
    protected array $numbers;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->numbers = [
            '1',
            '2',
            '26'
        ];
        $this->oddNumberService = new OddNumberService($this->numbers);
    }

    public function testOdd()
    {
        $odd = $this->oddNumberService->getOdd();
        $this->assertSame(1, $odd);
    }

}
